[package]
name = "waterui-str"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { workspace = true, features = ["derive"], optional = true }
typeshare.workspace = true

[features]
default = []
std = []
serde = ["dep:serde"]
