package dev.waterui.android.ffi;

import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;
import org.bytedeco.javacpp.tools.*;

/**
 * JavaCPP Parser configuration for waterui.h.
 * 
 * This file configures the JavaCPP Parser to generate Java bindings from the
 * C header file generated by Rust's cbindgen. The generated WaterUILib.java
 * provides low-level access to all WaterUI FFI functions.
 */
@Properties(target = "dev.waterui.android.ffi.WaterUILib", value = @Platform(include = "waterui.h", includepath = {
        "src/main/cpp/" }, library = "waterui_app"))
public class WaterUIConfig implements InfoMapper {

    @Override
    public void map(InfoMap infoMap) {
        // ============================================================
        // Opaque pointer types - treat as Pointer
        // These are forward-declared structs with no definition exposed
        // ============================================================
        infoMap.put(new Info(
                // Core types
                "WuiEnv", "WuiAnyView", "WuiAnyViews", "WuiAction",
                "WuiColor", "WuiFont", "WuiLayout", "WuiDynamic",
                "WuiRendererView", "WuiTabContent",

                // Binding types
                "Binding_AnyView", "Binding_Color", "Binding_Font", "Binding_Id",
                "Binding_Str", "Binding_bool", "Binding_f32", "Binding_f64", "Binding_i32",
                "WuiBinding_AnyView", "WuiBinding_Color", "WuiBinding_Font", "WuiBinding_Id",
                "WuiBinding_Str", "WuiBinding_Volume", "WuiBinding_bool",
                "WuiBinding_f32", "WuiBinding_f64", "WuiBinding_i32",

                // Computed types
                "WuiComputed_AnyView", "WuiComputed_AnyViews_AnyView", "WuiComputed_Color",
                "WuiComputed_ColorScheme", "WuiComputed_Font", "WuiComputed_Id",
                "WuiComputed_LivePhotoSource", "WuiComputed_ResolvedColor", "WuiComputed_ResolvedFont",
                "WuiComputed_Str", "WuiComputed_StyledStr", "WuiComputed_Vec_PickerItem_Id",
                "WuiComputed_Vec_TableColumn", "WuiComputed_Video",
                "WuiComputed_bool", "WuiComputed_f32", "WuiComputed_f64", "WuiComputed_i32",

                // Watcher types
                "WuiWatcher_AnyView", "WuiWatcher_AnyViews_AnyView", "WuiWatcher_Color",
                "WuiWatcher_ColorScheme", "WuiWatcher_Font", "WuiWatcher_Id",
                "WuiWatcher_LivePhotoSource", "WuiWatcher_ResolvedColor", "WuiWatcher_ResolvedFont",
                "WuiWatcher_Str", "WuiWatcher_StyledStr", "WuiWatcher_Vec_PickerItem_Id",
                "WuiWatcher_Vec_TableColumn", "WuiWatcher_Video",
                "WuiWatcher_bool", "WuiWatcher_f32", "WuiWatcher_f64", "WuiWatcher_i32",

                // Guard and metadata
                "WuiWatcherGuard", "WuiWatcherMetadata").pointerTypes("Pointer"));

        // ============================================================
        // Enums - keep as int for simplicity
        // ============================================================
        infoMap.put(new Info(
                "WuiAnimation", "WuiAxis", "WuiFontWeight", "WuiKeyboardType",
                "WuiProgressStyle", "WuiRendererBufferFormat",
                "WuiColorScheme", "WuiColorSlot", "WuiFontSlot").valueTypes("int").pointerTypes("IntPointer"));

        // ============================================================
        // Struct mappings
        // ============================================================

        // WuiStr is a wrapper around WuiArray_u8
        infoMap.put(new Info("WuiStr").pointerTypes("WuiStr"));

        // Array types
        infoMap.put(new Info("WuiArray", "WuiArray_u8", "WuiArray_____WuiAnyView",
                "WuiArray_WuiProposalSize", "WuiArray_WuiChildMetadata",
                "WuiArray_WuiRect", "WuiArray_WuiStyledChunk",
                "WuiArray_WuiTableColumn", "WuiArray_WuiPickerItem").pointerTypes("Pointer"));

        // VTable types - skip these as they contain function pointers
        infoMap.put(new Info("WuiArrayVTable", "WuiArrayVTable_u8",
                "WuiArrayVTable_____WuiAnyView", "WuiArrayVTable_WuiProposalSize",
                "WuiArrayVTable_WuiChildMetadata", "WuiArrayVTable_WuiRect",
                "WuiArrayVTable_WuiStyledChunk", "WuiArrayVTable_WuiTableColumn",
                "WuiArrayVTable_WuiPickerItem").skip());

        // Slice types
        infoMap.put(new Info("WuiArraySlice", "WuiArraySlice_u8",
                "WuiArraySlice_____WuiAnyView", "WuiArraySlice_WuiProposalSize",
                "WuiArraySlice_WuiChildMetadata", "WuiArraySlice_WuiRect",
                "WuiArraySlice_WuiStyledChunk", "WuiArraySlice_WuiTableColumn",
                "WuiArraySlice_WuiPickerItem").pointerTypes("Pointer"));

        // ============================================================
        // Data structs - generate proper classes
        // ============================================================
        infoMap.put(new Info("WuiResolvedColor").pointerTypes("WuiResolvedColor"));
        infoMap.put(new Info("WuiResolvedFont").pointerTypes("WuiResolvedFont"));
        infoMap.put(new Info("WuiProposalSize").pointerTypes("WuiProposalSize"));
        infoMap.put(new Info("WuiSize").pointerTypes("WuiSize"));
        infoMap.put(new Info("WuiPoint").pointerTypes("WuiPoint"));
        infoMap.put(new Info("WuiRect").pointerTypes("WuiRect"));
        infoMap.put(new Info("WuiChildMetadata").pointerTypes("WuiChildMetadata"));
        infoMap.put(new Info("WuiId").pointerTypes("WuiId"));
        infoMap.put(new Info("WuiRange_f64").pointerTypes("WuiRange_f64"));
        infoMap.put(new Info("WuiRange_i32").pointerTypes("WuiRange_i32"));

        // View structs
        infoMap.put(new Info("WuiButton").pointerTypes("WuiButton"));
        infoMap.put(new Info("WuiText").pointerTypes("WuiText"));
        infoMap.put(new Info("WuiTextField").pointerTypes("WuiTextField"));
        infoMap.put(new Info("WuiToggle").pointerTypes("WuiToggle"));
        infoMap.put(new Info("WuiSlider").pointerTypes("WuiSlider"));
        infoMap.put(new Info("WuiStepper").pointerTypes("WuiStepper"));
        infoMap.put(new Info("WuiPicker").pointerTypes("WuiPicker"));
        infoMap.put(new Info("WuiPickerItem").pointerTypes("WuiPickerItem"));
        infoMap.put(new Info("WuiProgress").pointerTypes("WuiProgress"));
        infoMap.put(new Info("WuiScrollView").pointerTypes("WuiScrollView"));
        infoMap.put(new Info("WuiContainer").pointerTypes("WuiContainer"));
        infoMap.put(new Info("WuiFixedContainer").pointerTypes("WuiFixedContainer"));

        // Text styling
        infoMap.put(new Info("WuiTextStyle").pointerTypes("WuiTextStyle"));
        infoMap.put(new Info("WuiStyledChunk").pointerTypes("WuiStyledChunk"));
        infoMap.put(new Info("WuiStyledStr").pointerTypes("WuiStyledStr"));

        // ============================================================
        // Function pointer callbacks - skip them entirely
        // These are handled by the manual JNI code
        // ============================================================
        infoMap.put(new Info("void (*)(void*)").skip());
        infoMap.put(new Info("struct WuiArraySlice (*)(const void*)").skip());
        infoMap.put(new Info("void (*)(void *, bool, WuiWatcherMetadata *)").skip());
        infoMap.put(new Info("void (*)(void *, int32_t, WuiWatcherMetadata *)").skip());
        infoMap.put(new Info("void (*)(void *, double, WuiWatcherMetadata *)").skip());
        infoMap.put(new Info("void (*)(void *, WuiStr, WuiWatcherMetadata *)").skip());
        infoMap.put(new Info("void (*)(void *, WuiStyledStr, WuiWatcherMetadata *)").skip());
        infoMap.put(new Info("void (*)(void *, WuiResolvedColor, WuiWatcherMetadata *)").skip());
        infoMap.put(new Info("void (*)(void *, WuiResolvedFont, WuiWatcherMetadata *)").skip());
        infoMap.put(new Info("void (*)(void *, WuiColorScheme, WuiWatcherMetadata *)").skip());
        infoMap.put(new Info("void (*)(void *, WuiArray_WuiPickerItem, WuiWatcherMetadata *)").skip());
        infoMap.put(new Info("void (*)(void *, WuiAnyView *, WuiWatcherMetadata *)").skip());

        // Skip ALL functions that use callbacks - these are handled by manual JNI
        // Watcher creation functions
        infoMap.put(new Info("waterui_new_watcher_bool").skip());
        infoMap.put(new Info("waterui_new_watcher_i32").skip());
        infoMap.put(new Info("waterui_new_watcher_f32").skip());
        infoMap.put(new Info("waterui_new_watcher_f64").skip());
        infoMap.put(new Info("waterui_new_watcher_str").skip());
        infoMap.put(new Info("waterui_new_watcher_styled_str").skip());
        infoMap.put(new Info("waterui_new_watcher_resolved_color").skip());
        infoMap.put(new Info("waterui_new_watcher_resolved_font").skip());
        infoMap.put(new Info("waterui_new_watcher_color_scheme").skip());
        infoMap.put(new Info("waterui_new_watcher_picker_items").skip());
        infoMap.put(new Info("waterui_new_watcher_any_view").skip());
        infoMap.put(new Info("waterui_new_watcher_color").skip());
        infoMap.put(new Info("waterui_new_watcher_font").skip());
        infoMap.put(new Info("waterui_new_watcher_id").skip());
        infoMap.put(new Info("waterui_new_watcher_video").skip());
        infoMap.put(new Info("waterui_new_watcher_live_photo_source").skip());
        infoMap.put(new Info("waterui_new_watcher_views").skip());
        infoMap.put(new Info("waterui_new_watcher_table_cols").skip());
        infoMap.put(new Info("waterui_new_watcher_guard").skip());

        // Computed creation functions (with callbacks)
        infoMap.put(new Info("waterui_new_computed_resolved_color").skip());
        infoMap.put(new Info("waterui_new_computed_resolved_font").skip());
        infoMap.put(new Info("waterui_new_computed_color_scheme").skip());

        // NonNull is just void*
        infoMap.put(new Info("NonNull").valueTypes("Pointer"));

        // Url is an alias for WuiStr
        infoMap.put(new Info("Url").pointerTypes("WuiStr"));
    }
}
