name: Android Backend CI

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

jobs:
  build:
    name: Build Android Backend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout android-backend repository
        uses: actions/checkout@v4
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
      - name: Build with Gradle
        run: ./gradlew build

  e2e-test:
    name: End-to-end Test
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Determine waterui branch
        id: get_waterui_branch
        run: |
          if [ "${{ github.ref_name }}" = "dev" ] || [ "${{ github.base_ref }}" = "dev" ]; then
            echo "branch=dev" >> $GITHUB_OUTPUT
          else
            echo "branch=main" >> $GITHUB_OUTPUT
          fi
      - name: Checkout waterui repository
        uses: actions/checkout@v4
        with:
          repository: water-rs/waterui
          path: waterui
          ref: ${{ steps.get_waterui_branch.outputs.branch }}
      - name: Checkout android-backend repository
        uses: actions/checkout@v4
        with:
          path: waterui/backends/android
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
      - name: Install waterui-cli
        working-directory: waterui
        run: cargo install --path cli
      - name: Create test app
        working-directory: waterui
        run: water create --name "E2E Test" --directory e2e-test-app --bundle-identifier com.waterui.e2etest --yes --backend android --dev
      - name: Package Android app
        working-directory: waterui
        run: water package --platform android --project e2e-test-app

  notify-waterui:
    name: Notify waterui repo
    runs-on: ubuntu-latest
    needs: e2e-test
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - name: Send repository_dispatch to waterui
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.SUBMODULE_UPDATE_PAT }}
          repository: water-rs/waterui
          event-type: update-android-backend
