name: Deploy Tutorial Book (mdBook + rustdoc) to Pages

on:
  push:
    branches: [main]
    paths:
      - tutorial-book/**
      - "**/*.rs"
      - "**/Cargo.toml"
      - "**/Cargo.lock"
      - ".github/workflows/deploy-book.yml"
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Rust toolchain
        uses: dtolnay/rust-toolchain@nightly

      - name: Cache cargo
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            ~/.cargo/bin
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: Install mdBook
        run: |
          if ! command -v mdbook >/dev/null; then
            cargo install mdbook --version 0.4.40
          fi

      # === NEW: Build rustdoc for the whole workspace ===
      - name: Build rustdoc (workspace)
        env:
          RUSTDOCFLAGS: "--cfg docsrs -D warnings"
        run: |
          cargo doc --workspace --no-deps --all-features
          CRATE=waterui
          echo '<meta http-equiv="refresh" content="0; url='"$CRATE"'/index.html">' > target/doc/index.html

      # === NEW: Mount rustdoc under mdBook's /api/ ===
      - name: Stage rustdoc into mdBook /api
        run: |
          rm -rf tutorial-book/src/api
          mkdir -p tutorial-book/src/api
          rsync -a --delete target/doc/ tutorial-book/src/api/

      - name: Build mdBook
        working-directory: tutorial-book
        run: mdbook build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: tutorial-book/book

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
